name: Python CI

on:
  pull_request:
    branches:
      - main  # Trigger the action when there's a PR to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the Python environment
      with:
        python-version: 3.9  # You can change the version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Set up mock data for tests
      run: |
        mkdir data
        echo "This is a mock system message" > data/system_message.txt
        echo "This is a mock example" > data/example.txt
        mkdir data/persistent_memory_storage

    - name: Create test JSON file
      run: |
        echo '{
          "person": {
            "name": "Joe Smith",
            "age": 99,
            "location": "Nowhere",
            "contact": {
              "email": "email@email.com"
            }
          }
        }' > data/mitchell.json

    - name: Set OpenAI API Key as an Environment Variable
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV  # Set the secret as an environment variable

    - name: Run tests with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Pass the secret to the pytest step
      run: |
        pytest  # Run the tests
